# Generated by Django 2.2 on 2020-06-29 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('imagen_presentacion', models.ImageField(null=True, upload_to='media')),
                ('descripcion', models.TextField(max_length=500)),
                ('precio', models.FloatField(default=0.0)),
                ('descuento', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenado', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Articulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin categoria', max_length=100)),
                ('descripcion', models.CharField(default='Sin descripcion', max_length=100)),
                ('color_descriptivo', models.CharField(default='black', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_referencia', models.CharField(max_length=100)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Numero de contacto', max_length=128, region=None)),
                ('direccion_especifica', models.CharField(max_length=50)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('provincia', models.CharField(max_length=50)),
                ('cuidad', models.CharField(max_length=50)),
                ('codigo_postal', models.IntegerField()),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenRefencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media')),
                ('descripcion', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charger_id', models.CharField(max_length=50)),
                ('total_pago', models.FloatField()),
                ('timestap', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('texto', models.TextField(max_length=500)),
                ('texto_pequeño', models.TextField(max_length=500)),
                ('posicion', models.CharField(choices=[('C', 'Centro'), ('D', 'Derecha')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now=True)),
                ('fecha_pedido', models.DateTimeField()),
                ('ordenado', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('articulos_pedidos', models.ManyToManyField(to='core.ArticuloPedido')),
                ('direccion_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Direccion')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categorias'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen_referencia',
            field=models.ManyToManyField(to='core.ImagenRefencia'),
        ),
    ]
