# Generated by Django 2.2 on 2020-03-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('texto', models.TextField(max_length=500)),
                ('texto_pequeño', models.TextField(max_length=500)),
            ],
        ),
    ]
