# Generated by Django 2.2 on 2020-03-21 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='posicion',
            field=models.CharField(choices=[('C', 'Centro'), ('D', 'Derecha')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
