# Generated by Django 2.2 on 2020-03-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slider_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenRefencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media')),
                ('descripcion', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=500)),
                ('imagen_referencia', models.ManyToManyField(to='core.ImagenRefencia')),
            ],
        ),
    ]
