# Generated by Django 2.2 on 2020-03-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200321_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descuento',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
    ]
