# Generated by Django 2.2 on 2020-03-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200321_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen_presentacion',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
