# Generated by Django 2.2 on 2020-03-22 03:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_articulo_imagen_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenrefencia',
            name='Articulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Articulo'),
            preserve_default=False,
        ),
    ]
