# Generated by Django 2.2 on 2020-03-22 04:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_imagenrefencia_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin categoria', max_length=100)),
                ('descripcion', models.CharField(default='Sin descripcion', max_length=100)),
                ('color_descriptivo', models.CharField(default='black', max_length=9)),
            ],
        ),
        
    ]
